"""Lightweight research infrastructure for leakage-safe GI-VQA experiments."""

from .audit import (
    SplitAudit,
    SplitAuditReport,
    SplitLeakageError,
    assert_disjoint_source_images,
    audit_jsonl_splits,
    audit_records,
)
from .backends import (
    AttributionError,
    AttributionResult,
    BackendCompatibilityError,
    BackendDependencyError,
    BackendProvenance,
    GenerationResult,
    PaliGemmaBackend,
    PreparedInput,
    ScoreVerification,
    TargetScore,
    VisionLanguageBackend,
)
from .config import ConfigError, config_sha256, load_config, validate_config
from .identifiers import (
    RecordFormatError,
    canonical_text,
    question_text,
    source_image_id,
    stable_item_id,
)
from .jsonl import JsonlDecodeError, iter_jsonl, read_jsonl, write_jsonl_atomic
from .model_spec import (
    PALIGEMMA_BACKEND,
    PALIGEMMA_MODEL_SPEC_SCHEMA,
    PaliGemmaModelSpec,
)
from .provenance import (
    MANIFEST_SCHEMA_VERSION,
    build_run_manifest,
    canonical_json_sha256,
    file_fingerprint,
    file_sha256,
    load_run_manifest,
    write_run_manifest,
)
from .shards import (
    DuplicateRecordIdError,
    ExpectedIdMismatchError,
    OutputExistsError,
    RecordIdError,
    ShardMergeReport,
    ShardValidation,
    ShardValidationError,
    merge_jsonl_shards_atomic,
    validate_jsonl_shards,
)
from .splits import (
    CONTRACT_RESERVED_SOURCE_IDS,
    GROUPED_SPLIT_SCHEMA_VERSION,
    SplitBuildError,
    SplitBuildPaths,
    build_grouped_splits,
    select_smoke_records,
    verify_grouped_split_artifacts,
)

__all__ = [
    "AttributionError",
    "AttributionResult",
    "BackendCompatibilityError",
    "BackendDependencyError",
    "BackendProvenance",
    "GenerationResult",
    "JsonlDecodeError",
    "MANIFEST_SCHEMA_VERSION",
    "PALIGEMMA_BACKEND",
    "PALIGEMMA_MODEL_SPEC_SCHEMA",
    "PaliGemmaBackend",
    "PaliGemmaModelSpec",
    "PreparedInput",
    "ScoreVerification",
    "RecordFormatError",
    "RecordIdError",
    "ConfigError",
    "CONTRACT_RESERVED_SOURCE_IDS",
    "GROUPED_SPLIT_SCHEMA_VERSION",
    "SplitAudit",
    "SplitAuditReport",
    "SplitBuildError",
    "SplitBuildPaths",
    "SplitLeakageError",
    "TargetScore",
    "VisionLanguageBackend",
    "ShardMergeReport",
    "ShardValidation",
    "ShardValidationError",
    "DuplicateRecordIdError",
    "ExpectedIdMismatchError",
    "OutputExistsError",
    "assert_disjoint_source_images",
    "audit_jsonl_splits",
    "audit_records",
    "build_run_manifest",
    "build_grouped_splits",
    "canonical_json_sha256",
    "canonical_text",
    "config_sha256",
    "file_fingerprint",
    "file_sha256",
    "iter_jsonl",
    "load_config",
    "load_run_manifest",
    "question_text",
    "read_jsonl",
    "merge_jsonl_shards_atomic",
    "source_image_id",
    "stable_item_id",
    "select_smoke_records",
    "validate_jsonl_shards",
    "verify_grouped_split_artifacts",
    "validate_config",
    "write_jsonl_atomic",
    "write_run_manifest",
]
